version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql
    ports:
      - 1433:1433
    volumes:
      - ./tmp:/tmp
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Str0ngPass!