assignment_solution:
  outputs:

    dev:
      type: postgres
      threads: 2
      host: pg
      port: 5432
      user: root
      pass: root
      dbname: dellstore
      schema: public

  target: dev
